version: "3"
services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SYMFONY__ENV__DATABASE_DRIVER=${SYMFONY__ENV__DATABASE_DRIVER}
      - SYMFONY__ENV__DATABASE_HOST=${SYMFONY__ENV__DATABASE_HOST}
      - SYMFONY__ENV__DATABASE_PORT=${SYMFONY__ENV__DATABASE_PORT}
      - SYMFONY__ENV__DATABASE_NAME=${SYMFONY__ENV__DATABASE_NAME}
      - SYMFONY__ENV__DATABASE_USER=${SYMFONY__ENV__DATABASE_USER}
      - SYMFONY__ENV__DATABASE_PASSWORD=${SYMFONY__ENV__DATABASE_PASSWORD}
      - SYMFONY__ENV__DATABASE_CHARSET=${SYMFONY__ENV__DATABASE_CHARSET}
      - SYMFONY__ENV__MAILER_HOST=${SYMFONY__ENV__MAILER_HOST}
      - SYMFONY__ENV__MAILER_USER=${SYMFONY__ENV__MAILER_USER}
      - SYMFONY__ENV__MAILER_PASSWORD=${SYMFONY__ENV__MAILER_PASSWORD}
      - SYMFONY__ENV__FROM_EMAIL=${SYMFONY__ENV__FROM_EMAIL}
      - SYMFONY__ENV__DOMAIN_NAME=${SYMFONY__ENV__DOMAIN_NAME}
      - SYMFONY__ENV__SERVER_NAME=${SYMFONY__ENV__SERVER_NAME}
    ports:
      - "8765:80"
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost",
        ]
      interval: 1m
      timeout: 3s
    depends_on:
      - db
      - redis
  db:
    image: mariadb
    container_name: wallabag-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s
  redis:
    image: redis:alpine
    container_name: wallabag-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
