version: '3
services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "8888:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://miniflux:${POSTGRES_PASSWORD}@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./miniflux-db:/var/lib/postgresql/data
volumes:
  miniflux-db:
