---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - APP_URL=${SERVER_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_HOST}
      - DB_PASS=${DB_PASSWD}
      - DB_DATABASE=${DB_NAME}
    volumes:
      - ./app/data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWD}
      - TZ=${TIME_ZONE}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
    volumes:
      - ./db/data:/config
    restart: unless-stopped
