version: '3.3'
services:

    prometheus:
        container_name: prometheus
        ports:
            - '9090:9090'
        volumes:
            - './config:/etc/prometheus'
        image: prom/prometheus
        restart: unless-stopped
