---
version: "2"
services:
  dashmachine:
    image: rmountjoy/dashmachine:latest
    container_name: dashmachine
    volumes:
      - ./config:/dashmachine/dashmachine/user_data
    ports:
      - 5000:5000
    restart: unless-stopped
