version: '3.3'
services:
  trilium:
    image: zadam/trilium:0.56-latest
    container_name: trilium
    ports:
      - '4000:8080'
    volumes:
      - './trilium-data:/home/node/trilium-data'
    restart: unless-stopped
