---
version: "2.1"
services:

  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    hostname: rss.kirk.blue
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    volumes:
      - ./data:/config
    ports:
      - 8888:80
    restart: unless-stopped
